# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18pfsSbQRXLeiEjuuEvfkePIaby9Kl4Ed
"""

def tbc_screening():
    print("Selamat datang di Aplikasi Skrining TBC")
    print("Silakan jawab beberapa pertanyaan untuk menentukan Indikasi Anda terkena TBC.")

    # Pertanyaan pertama
    answer1 = input("1. Apakah Anda saat ini sedang batuk lebih dari 2 minggu? (ya/tidak): ").strip().lower()
    if answer1 == "ya":
        print("Anda memiliki gejala batuk selama lebih dari 2 minggu, ini bisa menjadi indikasi TBC.")
        return "Terindikasi TBC"

    # Pertanyaan kedua
    answer2 = input("2. Apakah Anda pernah mengidap TBC sebelumnya? (ya/tidak): ").strip().lower()
    if answer2 == "ya":
        print("Anda pernah mengidap TBC sebelumnya, ini bisa menjadi risiko tambahan.")
        return "Terindikasi TBC"

    # Pertanyaan ketiga
    answer3 = input("3. Apakah Anda mengalami demam lebih dari 2 minggu? (ya/tidak): ").strip().lower()
    if answer3 == "ya":
        print("Anda mengalami demam, hal ini bisa jadi gejala TBC")
        return "Terindikasi TBC"

    # Pertanyaan keempat
    answer4 = input("4. Apakah anda mengalami turunnya berat badan yang drastis? (ya/tidak): ").strip().lower()
    if answer4 == "ya":
        print("Anda mengalami turunnya berat badan secara drastis, kemungkinan gejala TBC")
        return "Terindikasi TBC"

    # Pertanyaan kelima
    answer5 = input("5. Apakah anda berkeringat di malam hari tanpa sebab? (ya/tidak): ").strip().lower()
    if answer5 == "ya":
        print("Anda berkeringat di malam hari tanpa sebab, kemungkinan gejala TBC")
        return "Terindikasi TBC"

    # Jika tidak ada tanda-tanda TBC dari kedua pertanyaan
    print("Anda tidak memiliki tanda-tanda risiko TBC berdasarkan jawaban Anda.")
    return "Tidak Terindikasi TBC"

if __name__ == "__main__":
    hasil_skrining = tbc_screening()
    print(f"Hasil Skrining TBC: {hasil_skrining}")